tasks
meghnaneelayavalasa/2.1-2.5 pull request #1
Opened 2022-05-24 12:48 UTC by meghnaneelayavalasa

2.1-2.5

2022-06-02 04:55 UTC, SurajPareek01 requested changes

2022-06-02 04:55 UTC, SurajPareek01 commented on 2.1/Basic Mathematical Operations.js
> +            return 0;
Can we have the devide by zero check here?

2022-06-02 04:55 UTC, SurajPareek01 commented on 2.1/Transportation on vacation.js
> +  if(d>=7)
Please avoid using of magic numbers;

2022-06-02 04:55 UTC, SurajPareek01 commented on 2.2/Middle Character.js
> +  if(s.length % 2 == 1) {
please use strict type checking ( === )

2022-06-02 04:55 UTC, SurajPareek01 commented on 2.3/Can you keep a secret.js
> + getSecret : function() {
please beautify this code.

2022-06-02 04:55 UTC, SurajPareek01 commented on 2.4/A Chain adding function.js
> +  const f = x => add(n + x)
please beautify this code

2022-06-02 04:55 UTC, SurajPareek01 commented on 2.3/prefill an array.js
> +    arr = []
please use semi-colon;

2022-06-02 04:55 UTC, SurajPareek01 commented on 2.2/Middle Character.js
> +  return s.substring(position, position + length)
please use semi-colon;

2022-06-02 04:55 UTC, SurajPareek01 commented on 2.4/Using closures to share class state.js
> +        sum += cats[i].weight
please use semi-colon

2022-06-02 04:55 UTC, SurajPareek01 commented on 2.5/Array_Helpers.js
> +Array.prototype.square = function () { return this.map(function (n) { return n * n; }); }
Where is 'numbers' defined? It won't work.

2022-06-20 06:26 UTC, SurajPareek01 approved these changes

2022-06-21 10:11 UTC, meghnaneelayavalasa commented
Reviewed

2022-06-21 10:11 UTC, closed without merging